In [2]:
import pandas as pd

In [3]:
df=pd.read_excel(r"C:\Users\lavan\Desktop\ML_projects\ml_training\fd_data_5000_rows.xlsx")

In [4]:
df.head()

   srno    person  amount     fdno   interest     bank        date
0     1  Person_1  314037  15081625      7.92   Bank_6  29/08/2035
1     2  Person_2  709132   4530825      8.72   Bank_3  01/01/2035
2     3  Person_3  354311  54783891      7.87   Bank_7  20/09/2035
3     4  Person_4  957716  94587851      9.48  Bank_10  21/09/2030
4     5  Person_5  374453   1322946      7.45   Bank_1  29/02/2032

In [5]:
df[['day', 'month', 'year']] = df['date'].str.split('/',expand=True)

In [6]:
df.head(10)

,srno,person,amount,fdno,interest,bank,date,day,month,year
0,1,Person_1,314037,15081625,7.92,Bank_6,29/08/2035,29,08,2035
1,2,Person_2,709132,4530825,8.72,Bank_3,01/01/2035,01,01,2035
2,3,Person_3,354311,54783891,7.87,Bank_7,20/09/2035,20,09,2035
3,4,Person_4,957716,94587851,9.48,Bank_10,21/09/2030,21,09,2030
4,5,Person_5,374453,1322946,7.45,Bank_1,29/02/2032,29,02,2032
5,6,Person_6,910238,6380028,8.89,Bank_9,04/12/2031,04,12,2031
6,7,Person_7,290294,43716446,7.42,Bank_9,08/03/2028,08,03,2028
7,8,Person_8,378307,43651661,8.31,Bank_3,30/12/2032,30,12,2032
8,9,Person_9,351388,26090329,9.90,Bank_9,18/09/2034,18,09,2034
9,10,Person_10,748218,15384736,9.72,Bank_9,04/02/2030,04,02,2030

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   srno      5000 non-null   int64
 1   person    5000 non-null   str
 2   amount    5000 non-null   int64
 3   fdno      5000 non-null   int64
 4   interest  5000 non-null   float64
 5   bank      5000 non-null   str
 6   date      5000 non-null   str
 7   day       5000 non-null   str
 8   month     5000 non-null   str
 9   year      5000 non-null   str
dtypes: float64(1), int64(3), str(6)
memory usage: 390.8 KB

In [8]:
df['principal']=df['amount']+(df['amount']*df['interest'])

In [9]:
df

,srno,person,amount,fdno,interest,bank,date,day,month,year,principal
0,1,Person_1,314037,15081625,7.92,Bank_6,29/08/2035,29,08,2035,2801210.04
1,2,Person_2,709132,4530825,8.72,Bank_3,01/01/2035,01,01,2035,6892763.04
2,3,Person_3,354311,54783891,7.87,Bank_7,20/09/2035,20,09,2035,3142738.57
3,4,Person_4,957716,94587851,9.48,Bank_10,21/09/2030,21,09,2030,10036863.68
4,5,Person_5,374453,1322946,7.45,Bank_1,29/02/2032,29,02,2032,3164127.85
...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,Person_46,721303,31410919,8.91,Bank_1,06/04/2029,06,04,2029,7148112.73
4996,4997,Person_47,173901,19346554,7.32,Bank_7,17/07/2034,17,07,2034,1446856.32
4997,4998,Person_48,196370,99476879,9.93,Bank_6,28/11/2026,28,11,2026,2146324.10
4998,4999,Person_49,472088,34280664,7.11,Bank_8,29/11/2032,29,11,2032,3828633.68
4999,5000,Person_50,411411,91981075,7.21,Bank_10,19/09/2026,19,09,2026,3377684.31

In [10]:
df_1=df.sort_values(['principal'],ascending=False)

In [13]:
df_1.groupby(['person','principal'])

In [19]:
df_1

,srno,person,amount,fdno,interest,bank,date,day,month,year,principal
4658,4659,Person_9,990154,45809215,9.98,Bank_9,24/10/2027,24,10,2027,10871890.92
564,565,Person_15,995307,96822659,9.92,Bank_4,02/12/2031,02,12,2031,10868752.44
1411,1412,Person_12,983839,64945021,9.99,Bank_4,10/03/2029,10,03,2029,10812390.61
2995,2996,Person_46,989007,29984755,9.84,Bank_1,07/03/2035,07,03,2035,10720835.88
4220,4221,Person_21,999029,56899737,9.73,Bank_6,30/10/2026,30,10,2026,10719581.17
...,...,...,...,...,...,...,...,...,...,...,...
203,204,Person_4,104822,28090884,7.16,Bank_3,16/03/2030,16,03,2030,855347.52
4460,4461,Person_11,100735,42663213,7.43,Bank_8,15/02/2031,15,02,2031,849196.05
3106,3107,Person_7,100997,77773279,7.30,Bank_8,16/04/2035,16,04,2035,838275.10
3022,3023,Person_23,103794,2405295,7.02,Bank_9,28/09/2031,28,09,2031,832427.88
3795,3796,Person_46,102789,93002675,7.05,Bank_6,30/08/2029,30,08,2029,827451.45

In [20]:
df_2=df.sort_values(['interest'],ascending=False)

In [ ]:
df_2

In [39]:
df_1.groupby(['person','interest']).count()

                   srno  amount  fdno   bank  date  day  month  year  \
person   interest
Person_1 7.05         1       1      1     1     1    1      1     1
         7.07         1       1      1     1     1    1      1     1
         7.09         1       1      1     1     1    1      1     1
         7.12         1       1      1     1     1    1      1     1
         7.15         1       1      1     1     1    1      1     1
...                 ...     ...    ...   ...   ...  ...    ...   ...
Person_9 9.90         2       2      2     2     2    2      2     2
         9.91         1       1      1     1     1    1      1     1
         9.96         1       1      1     1     1    1      1     1
         9.97         2       2      2     2     2    2      2     2
         9.98         1       1      1     1     1    1      1     1

                   principal
person   interest
Person_1 7.05              1
         7.07              1
         7.09              1
         7.12              1
         7.15              1
...                      ...
Person_9 9.90              2
         9.91              1
         9.96              1
         9.97              2
         9.98              1

[4297 rows x 9 columns]